### ISSUE TITLE
Build de Travis-CI falla pero non é por probas que non pasen

### ISSUE THREAD

**Issue by lauramcastro** [heishiro-slash/VVS-Social#20]
A partir de agora, o único motivo aceptable para que as build de Travis fallen debería ser que estean fallando casos de proba (isto é, que haxa bugs detectados aínda non resoltos). O voso repositorio agora mesmo non se constrúe por algunha outra razón. Procurade que isto non ocorra.

**Comment by jmrio** [comment]
Tras revisar o historial de compilación de travis descubrín que as construcción empezaron a fallar no commit no que engadimos os test por defecto. 
O erro que nos da no log de Travis é "The command "ant test" exited with 1" e por mais que reviso non son capaz de atoparlle solución.

**Comment by lauramcastro** [comment]
O `exit 1` é a saída a liña de comandos do `ant test`, claro, pero o erro que vos da o `ant` en realidade é un erro de compilación un chisco antes, fixádevos: `invalid target release: 1.8`. Ademáis, apúntavos ao `build-imp.xml` como pista.

Á marxe de que ter esta estrutura dependente do IDE (o directorio `nbproject`, e un `pom.xml` baleiro que inclúe o `build-imp.xml` nese _path_) non é axeitado, e que sería preferible que tivesedes simplemente un `pom.xml` ben formado co contido pertinente, na documentación de Travis podedes ler que para proxectos Java se compila por defecto unha versión do JDK que non é a que o voso `build-imp.xml` especifica, xa que contén as seguintes liñas, que probablemente son a causa do conflito:

`<property name="default.javac.source" value="1.4"/>`
`<property name="default.javac.target" value="1.4"/>`

Intúo -non o comprobei, pero podedes facelo vós- que ese cambio apareceu ao incluír eses test por defecto, que probablemente coincidiu coa aparición da estrutura co `nbproject` (xa que me extraña que a tivesedes a semana anterior e non me dera de conta, teríavos aberto unha _issue_ para que o cambiasedes, como lle fixen a algún outro grupo).

En resumo: para solucionar o problema da compilación, asegurádevos de que ou lle dicides a Travis no .travis.yml que use a versión 1.4, ou que a vosa configuración para `ant` non ten esa restrición (a segunda é preferible, xa que a versión 1.4 é un tanto antiga). Para facelo ademais de xeito que o repositorio quede nun formato estándar, eliminade o `nbproject` como vos comento.

**Comment by jmrio** [comment]
He establecido que el proyecto se compile en java 1.8 y ahora travis lanza un error: package org.junit does not exist. He leído que se puede agregar de manera manual el jar de junit a la carpeta lib, pero no me parece demasiado correcto.
