### ISSUE TITLE
Eliminar el directorio `dist`

### ISSUE THREAD

**Issue by lauramcastro** [heishiro-slash/VVS-Social#3]
Aunque en un proyecto real mantendríamos este directorio con las versiones estables que hayamos ido publicando del mismo, en este caso no nos sirven de utilidad, y además casi todos los `jar` presentes en `dist/lib` están presentes en `lib` (que es la ubicación esperada). Algunos (`AbsoluteLayout.jar`, `swing-layout-1.0.4.jar`) sólo están en `dist/lib`, por lo que asumo que son dependencias antiguas que ya no son necesarias, ya que de lo contrario tendrían que estar en `lib` y la compilación estaría fallando.

**Comment by jmrio** [comment]
Solucionado
