### ISSUE TITLE
Reubicación y renombrado de `diagrama.svg`

### ISSUE THREAD

**Issue by lauramcastro** [heishiro-slash/VVS-Social#5]
Como documentación, debería ubicarse en el directorio correspondiente.

Además, sería de utilidad que su nombre fuese un poco más auto-descriptivo, sobre todo si durante el diseño de pruebas os encontráis con entidades que tengan estado y tenéis que hacer sus diagramas (en este caso, de estados).

**Comment by jmrio** [comment]
Solucionado
