### ISSUE TITLE
Eliminación del directorio `nbproject`

### ISSUE THREAD

**Issue by lauramcastro** [heishiro-slash/VVS-Social#6]
La presencia de este directorio no es estándar en proyectos Java; el IDE NetBeans crea el `build.xml` vacío y enlaza con el contenido distribuido en varios ficheros dentro de dicho directorio (`build-imp.xml` y `project.properties`).

Deberíais reubicar el contenido relevante únicamente en el fichero `build.xml`, y ubicar el `project.properties` en la raíz del repositorio, eliminando el directorio `nbproject`.

**Comment by jmrio** [comment]
Tras realizar las correcciones arriba descritas, netbeans deja de reconocer el proyecto como un proyecto. Esto es debido a que el IDE busca el project.properties en la carpeta nbproject. Me gustaría saber cómo podría solucionar esto. 

De momento mantengo esa carpeta  en mi copia local. Aun así para la ejecución del proyecto no la usa para nada.

**Comment by lauramcastro** [comment]
Realmente lo adecuado, cuando una herramienta no respeta las convenciones de un lenguaje, es que sólo las copias locales de las/los desarrolladores que usen esa herramienta estén adaptadas a ella, y que el repositorio se mantenga lo más estandarizado posible.

No sé qué ocurre en NetBeans si creáis un proyecto a partir del código descargado, seleccionando el `build.xml`/`project.properties` tal y como están. Quizás en ese caso no altere la estructura de ficheros y respete la que se encuentra, podéis probar. En caso contrario, aplica lo que os acabo de comentar.
